# Generated by Django 3.0.8 on 2020-07-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='occupants_count',
            field=models.IntegerField(default=1),
        ),
    ]
